### ISSUE TITLE
NPM-published version

### ISSUE THREAD

**Issue by egirshov** [gritzko/stream-url-ws#2]
Seems like the version published to npm as 0.1.1 does not match https://github.com/gritzko/stream-url-ws/commit/5d62cb6017566ee8b1e901867baa9f66683e19b6 (instead it is https://github.com/gritzko/stream-url-ws/commit/8a1688dd3243cb70a9535835cba1c57c449a6e3c). Could you please publish another release?

**Comment by gritzko** [comment]
You mean the published version is the "use `connection` event consistently" commit and you need precisely the version bump commit? That one did not pass tests.
